fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib"
    "augeas": "git://github.com/camptocamp/puppet-augeas"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql"
  symlinks:
    "galera": "#{source_dir}"
